spring:
    cloud:
        config:
            server:
                git:
                    uri: mock-uri
                    private-key: mock-private-key
                    ignoreLocalSshSettings: true
server:
    port: 0