services:
    mysql:
        image: mysql:8.0.39
        container_name: service-mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${USER_DB_NAME}
            TZ: Asia/Seoul
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - msa-network
    config-server:
        build:
            context: ./keupang-config-server
        ports:
            - "9000:9000"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - private_key=${private_key}
        networks:
            - msa-network

    api-gateway:
        build:
            context: ./keupang-gateway
        ports:
            - "8080:8080"
        depends_on:
            - eureka-server
        environment:
            - security_username=${security_username}
            - security_password=${security_password}
        networks:
            - msa-network

    service-user:
        build:
            context: ./keupang-user
        ports:
            - "8081:8081"
        deploy:
            mode: replicated
            restart_policy:
                condition: on-failure
        depends_on:
            - eureka-server
            - config-server
            - mysql
        environment:
            - security_username=${security_username}
            - security_password=${security_password}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - USER_DB_NAME=${USER_DB_NAME}
        networks:
            - msa-network

    service-product:
        build:
            context: ./keupang-product
        ports:
            - "8082:8082"
        depends_on:
            - eureka-server
            - config-server
        environment:
            - security_username=${security_username}
            - security_password=${security_password}
        networks:
            - msa-network

    eureka-server:
        build:
            context: ./keupang-eureka-server
        ports:
            - "8761:8761"
        networks:
            - msa-network
networks:
    msa-network:
        driver: bridge