spring:
    application:
        name: keupang-eureka-server

server:
    port: 8761

security:
    username: ${security_username:admin}
    password: ${security_password:admin}

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
