spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    application:
        name: auth
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

server:
    port: ${PORT:8080}


springdoc:
    api-docs:
        path: /auth/v3/api-docs
    swagger-ui:
        path: /auth/swagger-ui.html

openapi:
    service:
        # API Gateway 포트
        url: https://keupang-gateway.onrender.com

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: https://admin:admin@keupang-eureka.onrender.com/eureka/
    instance:
        instance-id: auth-service-${spring.application.instance-id:${random.value}}
        prefer-ip-address: true
